# Generated by Django 4.2.2 on 2025-09-20 06:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, dot/underscore/colon/hyphen.', regex='^[a-z0-9_.:-]+$')])),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Protected role; hide in admin for non-superusers.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, dot/underscore/colon/hyphen.', regex='^[a-z0-9_.:-]+$')])),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effect', models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], default='allow', max_length=8)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('org_key', models.CharField(blank=True, default='', help_text='Optional scope (e.g., department id). Leave blank for global.', max_length=128, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, dot/underscore/colon/hyphen.', regex='^[a-z0-9_.:-]+$')])),
                ('priority', models.IntegerField(default=0, help_text='Higher runs first.')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policy.action')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policy.resource')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policy.role')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org_key', models.CharField(blank=True, default='', help_text='Optional scope (e.g., department id). Leave blank for global.', max_length=128, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, dot/underscore/colon/hyphen.', regex='^[a-z0-9_.:-]+$')])),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='auth.group')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='policy.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role assignment',
                'verbose_name_plural': 'Role assignments',
                'indexes': [models.Index(fields=['role', 'user'], name='idx_assign_role_user'), models.Index(fields=['role', 'group'], name='idx_assign_role_group'), models.Index(fields=['org_key'], name='idx_assign_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('group__isnull', False), _connector='OR'), name='chk_assignment_has_user_or_group'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('role', 'user', 'org_key'), name='uniq_assignment_role_user_org'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('role', 'group', 'org_key'), name='uniq_assignment_role_group_org'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['role', 'resource', 'action'], name='idx_policy_rra'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['enabled', '-priority'], name='idx_policy_enabled_prio'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['org_key'], name='idx_policy_org'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('role', 'resource', 'action', 'org_key', 'priority'), name='uniq_policy_per_role_res_act_org_priority'),
        ),
    ]
