# Generated by Django 4.2.2 on 2025-09-21 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='condition_kind',
            field=models.CharField(choices=[('none', 'No condition (full access)'), ('own_dept', "User's department only"), ('assignment_scope', 'Assignment scope (org_key)'), ('specific_depts', 'Specific departments'), ('own_object', 'Only own objects (by field)'), ('own_author', 'Only where user is Author'), ('own_curator', 'Only where user is Curator'), ('specific_journals', 'Specific journals'), ('specific_doc_types', 'Specific document types'), ('specific_doc_subtypes', 'Specific document subtypes'), ('time_window', 'Within business hours'), ('advanced', 'Advanced (builder/JSON)')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_advanced_ast',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_doc_sub_type_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_doc_type_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_journal_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_owner_field',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_time_end_hhmm',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='policy',
            name='param_time_start_hhmm',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='policy',
            name='org_key',
            field=models.CharField(blank=True, default='', max_length=128, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits, dot/underscore/colon/hyphen.', regex='^[a-z0-9_.:-]+$')]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
