# Generated by Django 4.2.2 on 2025-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_policy_condition_kind_policy_param_advanced_ast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
