# Generated by Django 4.2.2 on 2025-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_policy_valid_from_policy_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='policy.resource'),
        ),
    ]
