# Generated by Django 4.2.2 on 2023-07-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('docflow', '0003_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='name',
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='docflow.basedocument'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file'),
        ),
    ]
