# Generated by Django 4.2.2 on 2023-07-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_alter_priority_options_deliverytype_name_en_and_more'),
        ('docflow', '0005_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='docflow.basedocument'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='docflow.basedocument'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.statusmodel'),
        ),
    ]
