# Generated by Django 4.2.2 on 2023-08-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0006_alter_documentfile_document_alter_reviewer_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='docflow.basedocument'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='docflow.basedocument'),
        ),
    ]
