# Generated by Django 4.2.2 on 2023-08-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0025_alter_district_region'),
        ('docflow', '0007_alter_documentfile_document_alter_reviewer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.statusmodel'),
        ),
    ]
