# Generated by Django 4.2.2 on 2023-08-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0026_documenttype_is_for_compose_journal_is_for_compose'),
        ('docflow', '0008_alter_reviewer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.statusmodel'),
        ),
    ]
