# Generated by Django 4.2.2 on 2023-09-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0010_reviewer_is_read_assignment_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='docflow.assignment'),
        ),
    ]
