# Generated by Django 4.2.2 on 2023-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_file_created_by_file_created_date_file_modified_by_and_more'),
        ('docflow', '0011_alter_assignee_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='files',
            field=models.ManyToManyField(blank=True, to='document.file'),
        ),
    ]
