# Generated by Django 4.2.2 on 2023-09-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0012_assignee_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='docflow.assignee'),
        ),
    ]
