# Generated by Django 4.2.2 on 2023-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0013_assignee_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='number_of_papers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
