# Generated by Django 4.2.2 on 2024-01-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0014_basedocument_number_of_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basedocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
