# Generated by Django 4.2.2 on 2024-01-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_file_extension_file_file_size'),
        ('docflow', '0015_assignee_is_active_assignment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='files',
            field=models.ManyToManyField(blank=True, to='document.file'),
        ),
    ]
