# Generated by Django 4.2.2 on 2024-02-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0016_reviewer_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
