# Generated by Django 4.2.2 on 2024-02-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_is_active_department_is_active_and_more'),
        ('docflow', '0017_basedocument_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
    ]
