# Generated by Django 4.2.2 on 2024-07-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0018_basedocument_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignee',
            options={'ordering': ['is_responsible']},
        ),
    ]
