# Generated by Django 4.2.2 on 2024-07-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0019_alter_assignee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignee',
            options={'ordering': ['-is_responsible']},
        ),
    ]
