# Generated by Django 4.2.2 on 2024-08-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0044_documentsubtype_name_en_documentsubtype_name_ru_and_more'),
        ('docflow', '0020_alter_assignee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='document_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.documentsubtype'),
        ),
    ]
