# Generated by Django 4.2.2 on 2024-08-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0028_businesstrip_company'),
        ('docflow', '0021_basedocument_document_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compose.compose'),
        ),
    ]
