# Generated by Django 5.2.8 on 2025-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0022_basedocument_compose'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='short_description',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
