# Generated by Django 4.2.2 on 2025-11-18 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0064_exceptionemployee_activation_comment_and_more'),
        ('docflow', '0022_basedocument_compose'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together={('document', 'user')},
        ),
        migrations.CreateModel(
            name='RegCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('next_no', models.PositiveIntegerField(default=1)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.journal')),
            ],
            options={
                'indexes': [models.Index(fields=['journal', 'year'], name='docflow_reg_journal_20a907_idx')],
                'unique_together': {('journal', 'year')},
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(max_length=24)),
                ('is_read', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docflow.assignment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflow.basedocument')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_read', 'created_date'], name='docflow_inb_user_id_f9dc3e_idx'), models.Index(fields=['user', 'kind', 'created_date'], name='docflow_inb_user_id_2547e2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inboxitem',
            constraint=models.UniqueConstraint(fields=('user', 'document', 'kind'), name='uniq_inbox_user_doc_kind'),
        ),
    ]
