# Generated by Django 4.2.2 on 2025-11-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0023_alter_reviewer_unique_together_regcounter_inboxitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docflow.reviewer'),
        ),
    ]
