# Generated by Django 4.2.2 on 2025-11-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0024_inboxitem_read_time_inboxitem_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together=set(),
        ),
    ]
