# Generated by Django 4.2.2 on 2025-11-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0023_basedocument_short_description'),
        ('docflow', '0025_alter_reviewer_unique_together'),
    ]

    operations = [
    ]
