# Generated by Django 4.2.2 on 2024-11-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newscontent_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AlterModelOptions(
            name='newscontent',
            options={'verbose_name': 'News Content', 'verbose_name_plural': 'News Contents'},
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'verbose_name': 'News Tag', 'verbose_name_plural': 'News Tags'},
        ),
    ]
