# Generated by Django 4.2.2 on 2024-11-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_news_options_alter_newscategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NewsViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='news.news')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Viewer',
                'verbose_name_plural': 'News Viewers',
            },
        ),
    ]
