# Generated by Django 4.2.2 on 2024-11-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_file_file'),
        ('news', '0004_news_view_counts_newsviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file'),
        ),
    ]
