# Generated by Django 4.2.2 on 2024-11-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_file_file'),
        ('news', '0005_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='galleries',
            field=models.ManyToManyField(blank=True, related_name='+', to='document.file'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='document.file'),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('quote', 'Quote')], max_length=25, null=True),
        ),
    ]
