# Generated by Django 4.2.2 on 2024-11-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_galleries_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
