# Generated by Django 4.2.2 on 2024-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newscategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('declined', 'Declined')], default='draft', max_length=50, null=True),
        ),
    ]
