# Generated by Django 4.2.2 on 2024-12-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_like_counts_newslike_newscomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscontent',
            options={'ordering': ['created_date'], 'verbose_name': 'News Content', 'verbose_name_plural': 'News Contents'},
        ),
    ]
