# Generated by Django 4.2.2 on 2024-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_newscontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
