# Generated by Django 4.2.2 on 2024-12-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newscategory_name_en_newscategory_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstag',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tags', to='news.newscategory'),
        ),
    ]
