# Generated by Django 4.2.2 on 2025-01-11 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0014_alter_news_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived'), ('declined', 'Declined')], default='draft', max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name_plural': 'News Moderation Histories',
            },
        ),
    ]
