# Generated by Django 4.2.2 on 2023-08-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0002_compose_short_description_composestatus_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='compose.compose'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='compose.compose'),
        ),
    ]
