# Generated by Django 4.2.2 on 2023-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0003_alter_approver_compose_alter_signer_compose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('service_letter', 'Service letter'), ('outgoing_letter', 'Outgoing letter')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compose',
            name='type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('service_letter', 'Service letter'), ('outgoing_letter', 'Outgoing letter')], max_length=100, null=True),
        ),
    ]
