# Generated by Django 4.2.2 on 2023-08-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_file_created_by_file_created_date_file_modified_by_and_more'),
        ('compose', '0004_alter_compose_sub_type_alter_compose_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='files',
            field=models.ManyToManyField(blank=True, to='document.file'),
        ),
        migrations.AlterField(
            model_name='compose',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('service_letter', 'Service letter'), ('outgoing_letter', 'Outgoing letter'), ('organizational_letter', 'Organizational letter')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compose',
            name='type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('service_letter', 'Service letter'), ('outgoing_letter', 'Outgoing letter'), ('organizational_letter', 'Organizational letter')], max_length=100, null=True),
        ),
    ]
