# Generated by Django 4.2.2 on 2023-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0005_compose_files_alter_compose_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composestatus',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
