# Generated by Django 4.2.2 on 2023-09-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0006_composestatus_is_approve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composestatus',
            options={'verbose_name_plural': 'Compose Statuses'},
        ),
        migrations.AddField(
            model_name='receiver',
            name='type',
            field=models.CharField(blank=True, choices=[('departments', 'Departments'), ('organizations', 'Organizations'), ('companies', 'Companies')], max_length=100, null=True),
        ),
    ]
