# Generated by Django 4.2.2 on 2023-09-25 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docflow', '0013_assignee_parent'),
        ('compose', '0008_compose_curator_alter_compose_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='registered_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_document', to='docflow.basedocument'),
        ),
        migrations.AddField(
            model_name='compose',
            name='replied_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_document', to='docflow.basedocument'),
        ),
    ]
