# Generated by Django 4.2.2 on 2023-12-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0010_composeversionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('inner', 'Service letter'), ('outgoing', 'Outgoing letter'), ('organizational_letter', 'Organizational letter')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compose',
            name='type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('inner', 'Service letter'), ('outgoing', 'Outgoing letter'), ('organizational_letter', 'Organizational letter')], max_length=100, null=True),
        ),
    ]
