# Generated by Django 4.2.2 on 2024-01-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0011_alter_compose_sub_type_alter_compose_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compose',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='composestatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='composeversionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
