# Generated by Django 4.2.2 on 2024-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0012_approver_is_active_compose_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='certificate_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
