# Generated by Django 4.2.2 on 2024-01-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0013_signer_certificate_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='pkcs7',
            field=models.TextField(blank=True, null=True),
        ),
    ]
