# Generated by Django 4.2.2 on 2024-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0014_signer_pkcs7'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='type',
            field=models.CharField(blank=True, choices=[('basic_signer', 'Basic signer'), ('signer', 'Signer'), ('invited', 'Invited')], default='signer', max_length=100, null=True),
        ),
    ]
