# Generated by Django 4.2.2 on 2024-02-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0015_signer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compose',
            name='title',
        ),
    ]
