# Generated by Django 4.2.2 on 2024-02-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0042_journal_code'),
        ('compose', '0016_remove_compose_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.documenttitle'),
        ),
    ]
