# Generated by Django 4.2.2 on 2024-02-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0017_compose_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='composestatus',
            name='declined_from_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='composestatus',
            name='declined_from_signer',
            field=models.BooleanField(default=False),
        ),
    ]
