# Generated by Django 4.2.2 on 2024-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0018_composestatus_declined_from_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='check_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
