# Generated by Django 4.2.2 on 2024-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0019_compose_check_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
