# Generated by Django 4.2.2 on 2024-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0020_compose_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('inner', 'Service letter'), ('outgoing', 'Outgoing letter'), ('organizational_letter', 'Organizational letter'), ('childcare_leave', 'Childcare leave'), ('annual_leave', 'Annual leave'), ('task_assignment', 'Task assignment'), ('disciplinary_action', 'Disciplinary action'), ('vacation_reschedule', 'Vacation reschedule'), ('resignation', 'Resignation'), ('funeral_leave', 'Funeral leave'), ('job_rotation', 'Job rotation'), ('paid_leave', 'Paid leave'), ('unpaid_leave', 'Unpaid leave'), ('study_leave', 'Study leave'), ('recall_from_leave', 'Recall from leave'), ('one_time_bonus', 'One time bonus'), ('military_leave', 'Military leave'), ('marriage_bonus', 'Marriage bonus'), ('child_bonus', 'Child bonus')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compose',
            name='type',
            field=models.CharField(blank=True, choices=[('notice', 'Notice'), ('inner', 'Service letter'), ('outgoing', 'Outgoing letter'), ('organizational_letter', 'Organizational letter'), ('application', 'Application')], max_length=100, null=True),
        ),
    ]
