# Generated by Django 4.2.2 on 2024-08-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0043_statusmodel_is_in_progress'),
        ('compose', '0021_alter_compose_sub_type_alter_compose_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compose',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='compose',
            name='type',
        ),
        migrations.AddField(
            model_name='compose',
            name='document_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.documentsubtype'),
        ),
    ]
