# Generated by Django 4.2.2 on 2024-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0022_remove_compose_sub_type_remove_compose_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='performers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='resolution_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
