# Generated by Django 4.2.2 on 2024-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0023_signer_performers_signer_resolution_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
