# Generated by Django 4.2.2 on 2024-08-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_position_iabs_level_code'),
        ('compose', '0027_businesstrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='company.company'),
        ),
    ]
