# Generated by Django 4.2.2 on 2024-08-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0028_businesstrip_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='type',
            field=models.CharField(blank=True, choices=[('basic_signer', 'Basic signer'), ('signer', 'Signer'), ('invited', 'Invited'), ('negotiator', 'Negotiator')], default='signer', max_length=100, null=True),
        ),
    ]
