# Generated by Django 4.2.2 on 2024-08-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0030_tripverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripverification',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip', to='compose.businesstrip'),
        ),
    ]
