# Generated by Django 4.2.2 on 2024-08-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_file_document_fi_key_38da3b_idx'),
        ('compose', '0031_alter_tripverification_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='file',
            field=models.ForeignKey(blank=True, help_text='After signing, the file will be saved as pdf', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='document.file'),
        ),
        migrations.AddField(
            model_name='tripverification',
            name='is_sender',
            field=models.BooleanField(default=False),
        ),
    ]
