# Generated by Django 4.2.2 on 2024-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0032_compose_file_tripverification_is_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripverification',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
