# Generated by Django 4.2.2 on 2024-08-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0034_negotiation_negotiationinstance_negotiator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationinstance',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
