# Generated by Django 4.2.2 on 2024-08-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0035_negotiationinstance_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compose.negotiationtype'),
        ),
    ]
