# Generated by Django 4.2.2 on 2024-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0037_tripexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexpense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
