# Generated by Django 4.2.2 on 2024-08-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0039_alter_negotiator_negotiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationinstance',
            name='negotiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compose.negotiation'),
        ),
    ]
