# Generated by Django 4.2.2 on 2024-08-22 18:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0041_negotiation_title_negotiationsubtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
