# Generated by Django 4.2.2 on 2024-08-22 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0042_negotiation_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiation',
            name='users',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
