# Generated by Django 4.2.2 on 2024-08-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0043_remove_negotiation_users_negotiation_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiator',
            name='negotiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiators', to='compose.negotiationinstance'),
        ),
    ]
