# Generated by Django 4.2.2 on 2024-08-24 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0044_alter_negotiator_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripverification',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='tripverification',
            name='arrived_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripverification',
            name='left_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left', to=settings.AUTH_USER_MODEL),
        ),
    ]
