# Generated by Django 4.2.2 on 2024-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0045_remove_tripverification_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
