# Generated by Django 4.2.2 on 2024-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0047_composelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='register_number_int',
            field=models.IntegerField(default=0),
        ),
    ]
