# Generated by Django 4.2.2 on 2024-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0048_compose_register_number_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
