# Generated by Django 4.2.2 on 2024-09-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0046_expensetype'),
        ('compose', '0049_compose_signed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='document_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.documentsubtype'),
        ),
    ]
