# Generated by Django 4.2.2 on 2024-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0050_tag_document_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='resolution_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
