# Generated by Django 4.2.2 on 2024-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0051_signer_resolution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='register_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
