# Generated by Django 4.2.2 on 2024-09-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0052_alter_compose_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
