# Generated by Django 4.2.2 on 2024-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0053_signer_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='for_new_users',
            field=models.BooleanField(default=False),
        ),
    ]
