# Generated by Django 4.2.2 on 2024-10-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0054_negotiation_for_new_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripverification',
            name='next_destination_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripverification',
            name='next_destination_type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('branch', 'Branch')], max_length=100, null=True),
        ),
    ]
