# Generated by Django 4.2.2 on 2024-10-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0055_tripverification_next_destination_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripverification',
            name='next_destination_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
