# Generated by Django 4.2.2 on 2024-11-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0056_alter_tripverification_next_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='end_date',
            field=models.DateField(blank=True, help_text='Attorney document end date', null=True),
        ),
        migrations.AddField(
            model_name='compose',
            name='start_date',
            field=models.DateField(blank=True, help_text='Attorney document start date', null=True),
        ),
        migrations.AddField(
            model_name='compose',
            name='user',
            field=models.ForeignKey(blank=True, help_text='For attorney documents and etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
