# Generated by Django 4.2.2 on 2024-12-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0057_compose_end_date_compose_start_date_compose_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='trip_notice_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
