# Generated by Django 4.2.2 on 2024-12-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0058_compose_trip_notice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='compose.compose'),
        ),
    ]
