# Generated by Django 4.2.2 on 2024-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0051_alter_country_options'),
        ('compose', '0060_tripverification_address_tripverification_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='locations',
            field=models.ManyToManyField(blank=True, to='reference.region'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='tags',
            field=models.ManyToManyField(blank=True, to='compose.tag'),
        ),
    ]
