# Generated by Django 4.2.2 on 2024-12-23 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0051_alter_country_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0062_flightbooking_passenger_flightsegment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightBooking',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='FlightSegment',
            new_name='BookingSegment',
        ),
    ]
