# Generated by Django 4.2.2 on 2024-12-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0063_rename_flightbooking_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.CharField(blank=True, choices=[('by_car', 'By car'), ('by_train', 'By train'), ('by_plane', 'By plane'), ('by_bus', 'By bus')], default='by_car', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='compose.bookingsegment'),
        ),
    ]
