# Generated by Django 4.2.2 on 2024-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0064_booking_route_alter_passenger_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsegment',
            name='segment_class',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First'), ('sleeper', 'Sleeper'), ('seat', 'Seat')], default=None, max_length=20, null=True),
        ),
    ]
