# Generated by Django 4.2.2 on 2024-12-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0068_remove_booking_trip_booking_compose_tripplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to='compose.compose'),
        ),
    ]
