# Generated by Django 4.2.2 on 2024-12-25 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0069_alter_tripplan_compose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplan',
            name='user',
        ),
        migrations.AddField(
            model_name='tripplan',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
