# Generated by Django 4.2.2 on 2024-12-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0070_remove_tripplan_user_tripplan_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsegment',
            name='departure_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='group_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
