# Generated by Django 4.2.2 on 2025-01-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0052_editablefield'),
        ('compose', '0072_visitedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripverification',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.region'),
        ),
    ]
