# Generated by Django 4.2.2 on 2025-01-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0073_tripverification_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedplace',
            name='trip_verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited_places', to='compose.tripverification'),
        ),
    ]
