# Generated by Django 4.2.2 on 2025-04-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0075_remove_visitedplace_address_remove_visitedplace_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripverification',
            old_name='address',
            new_name='arrived_address',
        ),
        migrations.RenameField(
            model_name='tripverification',
            old_name='lat',
            new_name='arrived_lat',
        ),
        migrations.RenameField(
            model_name='tripverification',
            old_name='lng',
            new_name='arrived_lng',
        ),
        migrations.AddField(
            model_name='tripverification',
            name='left_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripverification',
            name='left_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tripverification',
            name='left_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
