# Generated by Django 4.2.2 on 2025-04-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_region'),
        ('compose', '0076_rename_address_tripverification_arrived_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='sender_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_company', to='company.company'),
        ),
    ]
