# Generated by Django 4.2.2 on 2025-04-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_region'),
        ('compose', '0077_businesstrip_sender_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripverification',
            name='sender_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_sender_company', to='company.company'),
        ),
    ]
