# Generated by Django 4.2.2 on 2025-04-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0078_tripverification_sender_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripverification',
            name='sender_company',
        ),
    ]
