# Generated by Django 4.2.2 on 2025-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0079_remove_tripverification_sender_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='status',
            field=models.CharField(choices=[('not_started', 'Boshlanmagan'), ('on_trip', 'Xizmat safarida'), ('reporting', 'Hisobot topshrish'), ('closed', 'Yakunlangan')], default='not_started', max_length=20),
        ),
    ]
