# Generated by Django 4.2.2 on 2025-04-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0080_businesstrip_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstrip',
            old_name='status',
            new_name='trip_status',
        ),
    ]
