# Generated by Django 4.2.2 on 2025-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0081_rename_status_businesstrip_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripverification',
            name='next_destination_type',
            field=models.CharField(blank=True, choices=[('branch', 'Branch'), ('region', 'Region')], max_length=100, null=True),
        ),
    ]
