# Generated by Django 4.2.2 on 2025-05-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0083_iabsactionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iabsactionhistory',
            options={'verbose_name': 'IABS Action History', 'verbose_name_plural': 'IABS Action Histories'},
        ),
    ]
