# Generated by Django 4.2.2 on 2025-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0084_alter_iabsactionhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabsactionhistory',
            name='action',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('create', 'Create'), ('prolong', 'Prolong'), ('cancel', 'Cancel')], default='create'),
        ),
        migrations.AlterField(
            model_name='iabsactionhistory',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('create', 'Create'), ('prolong', 'Prolong'), ('cancel', 'Cancel')]),
        ),
    ]
