# Generated by Django 4.2.2 on 2025-05-17 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0085_iabsactionhistory_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabsactionhistory',
            name='compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compose.compose'),
        ),
    ]
