# Generated by Django 4.2.2 on 2025-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0086_iabsactionhistory_compose'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('branch', 'Branch')], default=None, max_length=20, null=True),
        ),
    ]
