# Generated by Django 4.2.2 on 2025-05-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0087_businesstrip_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('foreign', 'Foreign')], default='local', max_length=20, null=True),
        ),
    ]
