# Generated by Django 4.2.2 on 2025-06-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0088_alter_businesstrip_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabsactionhistory',
            name='request_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iabsactionhistory',
            name='response_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IABSRequestCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('create', 'Create'), ('prolong', 'Prolong'), ('cancel', 'Cancel')])),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('action_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_call_histories', to='compose.iabsactionhistory')),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
