# Generated by Django 4.2.2 on 2025-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0089_iabsactionhistory_request_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
