# Generated by Django 4.2.2 on 2025-06-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0090_alter_businesstrip_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
