# Generated by Django 4.2.2 on 2025-06-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0091_alter_businesstrip_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='compose.businesstrip'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('foreign', 'Foreign'), ('changed_local', 'Changed local'), ('changed_foreign', 'Changed foreign')], default='local', max_length=20, null=True),
        ),
    ]
