# Generated by Django 4.2.2 on 2025-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0091_alter_businesstrip_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabsactionhistory',
            name='endpoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('foreign', 'Foreign'), ('changed_local', 'Changed local'), ('changed_foreign', 'Changed foreign')], default='local', max_length=20, null=True),
        ),
    ]
