# Generated by Django 4.2.2 on 2025-06-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0092_businesstrip_parent_alter_businesstrip_trip_type'),
        ('compose', '0092_iabsactionhistory_endpoint_and_more'),
    ]

    operations = [
    ]
