# Generated by Django 4.2.2 on 2025-06-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0093_merge_20250612_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabsactionhistory',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('trip', 'Trip'), ('trip_extend', 'Trip Extend'), ('trip_cancel', 'Trip Cancel'), ('trip_prolong', 'Trip Prolong')], max_length=100, null=True),
        ),
    ]
