# Generated by Django 4.2.2 on 2025-06-23 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0094_iabsactionhistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_approvers', to=settings.AUTH_USER_MODEL),
        ),
    ]
