# Generated by Django 4.2.2 on 2025-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0095_approver_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='end_date_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
