# Generated by Django 4.2.2 on 2025-07-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0096_businesstrip_end_date_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabsactionhistory',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iabsrequestcallhistory',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
