# Generated by Django 4.2.2 on 2025-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0056_citydistance'),
        ('compose', '0097_iabsactionhistory_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='countries',
            field=models.ManyToManyField(blank=True, to='reference.country'),
        ),
    ]
