# Generated by Django 4.2.2 on 2025-09-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0098_businesstrip_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.CharField(blank=True, choices=[('by_car', 'By car'), ('by_train', 'By train'), ('by_plane', 'By plane'), ('by_bus', 'By bus'), ('by_service_car', 'By service car')], default='by_car', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='route',
            field=models.CharField(blank=True, choices=[('by_car', 'By car'), ('by_train', 'By train'), ('by_plane', 'By plane'), ('by_bus', 'By bus'), ('by_service_car', 'By service car')], default='by_car', max_length=30, null=True),
        ),
    ]
