# Generated by Django 4.2.2 on 2025-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0099_alter_booking_route_alter_businesstrip_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiator',
            name='dsi_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
