# Generated by Django 4.2.2 on 2025-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0100_negotiator_dsi_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
