# Generated by Django 4.2.2 on 2023-07-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_created_by_user_created_date_user_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
