# Generated by Django 4.2.2 on 2023-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_company_user_department_user_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name_plural': 'User Statuses'},
        ),
        migrations.AddField(
            model_name='user',
            name='begin_work_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tin',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
