# Generated by Django 4.2.2 on 2023-10-11 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_projectpermission_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='url_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
