# Generated by Django 4.2.2 on 2023-12-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_department_condition'),
        ('user', '0017_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='top_level_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_department', to='company.department'),
        ),
    ]
