# Generated by Django 4.2.2 on 2023-12-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_notificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
