# Generated by Django 4.2.2 on 2023-12-29 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_notificationtype_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='notificationtype',
            name='type',
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('description_uz', models.CharField(max_length=500, null=True)),
                ('description_ru', models.CharField(max_length=500, null=True)),
                ('description_en', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(blank=True, choices=[('approve', 'Approve'), ('review', 'Review'), ('sign', 'Sign'), ('assignment', 'Assignment')], max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.notificationmodel'),
        ),
    ]
