# Generated by Django 4.2.2 on 2024-01-23 04:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_notificationmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
