# Generated by Django 4.2.2 on 2024-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpermission',
            name='methods',
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='menu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='sub_menu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
