# Generated by Django 4.2.2 on 2024-03-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_projectpermission_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pinfl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
