# Generated by Django 4.2.2 on 2024-07-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='code_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='sort_ord',
            field=models.IntegerField(default=0),
        ),
    ]
