# Generated by Django 4.2.2 on 2024-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_userstatus_code_type_userstatus_sort_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='iabs_emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='iabs_staffing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
