# Generated by Django 4.2.2 on 2024-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_gender_user_iabs_emp_id_user_iabs_staffing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
