# Generated by Django 4.2.2 on 2024-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_mysalary_annualsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualsalary',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
