# Generated by Django 4.2.2 on 2024-08-08 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_annualsalary_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, null=True)),
                ('name', models.TextField(null=True)),
                ('date_oper', models.CharField(max_length=50, null=True)),
                ('inv_num', models.CharField(max_length=50, null=True)),
                ('qr_text', models.TextField(null=True)),
                ('responsible', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
