# Generated by Django 4.2.2 on 2024-08-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_userequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ldap_login',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
