# Generated by Django 4.2.2 on 2024-08-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_user_ldap_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cisco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='normalized_cisco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
