# Generated by Django 4.2.2 on 2024-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_user_cisco_user_email_user_normalized_cisco'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(to='user.projectpermission'),
        ),
    ]
