# Generated by Django 4.2.2 on 2024-08-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpermission',
            old_name='menu',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='projectpermission',
            name='sub_menu',
        ),
        migrations.RemoveField(
            model_name='projectpermission',
            name='type',
        ),
    ]
