# Generated by Django 4.2.2 on 2024-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_rename_menu_projectpermission_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='user.projectpermission'),
        ),
    ]
