# Generated by Django 4.2.2 on 2024-09-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_signermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.projectpermission'),
        ),
    ]
