# Generated by Django 4.2.2 on 2024-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_projectpermission_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpermission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectpermission',
            name='has_permission',
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
