# Generated by Django 4.2.2 on 2024-09-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_remove_projectpermission_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
