# Generated by Django 4.2.2 on 2024-09-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_projectpermission_name_en_projectpermission_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='user.rolemodel'),
        ),
    ]
