# Generated by Django 4.2.2 on 2024-09-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
