# Generated by Django 4.2.2 on 2024-09-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0046_expensetype'),
        ('user', '0044_alter_rolemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='doc_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.documentsubtype'),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.documenttype'),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.journal'),
        ),
    ]
