# Generated by Django 4.2.2 on 2024-09-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_projectpermission_doc_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpermission',
            options={'ordering': ['created_date']},
        ),
    ]
