# Generated by Django 4.2.2 on 2024-09-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_projectpermission_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpermission',
            old_name='doc_sub_type',
            new_name='document_sub_type',
        ),
        migrations.RenameField(
            model_name='projectpermission',
            old_name='doc_type',
            new_name='document_type',
        ),
    ]
