# Generated by Django 4.2.2 on 2024-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_rename_doc_sub_type_projectpermission_document_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpermission',
            name='all_visible',
            field=models.BooleanField(default=False),
        ),
    ]
