# Generated by Django 4.2.2 on 2024-10-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_projectpermission_all_visible'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email', 'pinfl', 'tin', 'table_number', 'unique_number', 'phone'], name='user_user_usernam_af13cf_idx'),
        ),
    ]
