# Generated by Django 4.2.2 on 2024-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_user_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='included_in_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='strict_condition',
            field=models.BooleanField(default=False),
        ),
    ]

