# Generated by Django 4.2.2 on 2024-11-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_user_passport_expiry_date_user_passport_issue_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passport_issue_place',
            new_name='passport_issued_by',
        ),
    ]
