# Generated by Django 4.2.2 on 2024-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_rename_passport_issue_place_user_passport_issued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='user.projectpermission'),
        ),
    ]
