# Generated by Django 4.2.2 on 2025-01-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
