# Generated by Django 4.2.2 on 2025-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_birth_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_mobile_number',
            field=models.BooleanField(default=False),
        ),
    ]
