# Generated by Django 4.2.2 on 2025-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_user_show_birth_date_user_show_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
