# Generated by Django 4.2.2 on 2025-05-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0082_alter_tripverification_next_destination_type'),
        ('user', '0068_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='trip_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compose.tripverification'),
        ),
    ]
