# Generated by Django 4.2.2 on 2025-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_userdevice_trip_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
