# Generated by Django 4.2.2 on 2025-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_user_otp_count_user_otp_received_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
