# Generated by Django 4.2.2 on 2025-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_user_leave_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='begin_work_date',
            field=models.DateField(blank=True, help_text='Date when the employee begins work', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date when the employee leaves the company', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='leave_end_date',
            field=models.DateField(blank=True, help_text='Date when the employee leave (vacation, sick leave, etc) ends', null=True),
        ),
    ]
