# Generated by Django 4.2.2 on 2025-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_alter_user_begin_work_date_alter_user_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
