# Generated by Django 4.2.2 on 2025-09-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_userfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hik_person_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
