# Generated by Django 4.2.2 on 2025-09-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_user_hik_person_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hik_person_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
