# Generated by Django 4.2.2 on 2025-10-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_alter_user_hik_person_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='is_reasonable',
            field=models.BooleanField(default=False),
        ),
    ]
