# Generated by Django 4.2.2 on 2025-10-16 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_workschedule'),
        ('user', '0078_userstatus_is_reasonable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hr.workschedule'),
        ),
    ]
