# Generated by Django 4.2.2 on 2025-10-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_user_work_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_schedule',
        ),
    ]
