# Generated by Django 4.2.2 on 2024-12-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageranking',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pageranking',
            name='rank',
            field=models.IntegerField(default=5),
        ),
    ]
