# Generated by Django 4.2.2 on 2025-02-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sqlquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlquery',
            options={'verbose_name': 'SQL Query', 'verbose_name_plural': 'SQL Queries'},
        ),
    ]
