# Generated by Django 4.2.2 on 2025-02-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sqlquery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='query_type',
            field=models.CharField(choices=[('employee_experience', 'Employee experience'), ('by_gender', 'Group By Gender'), ('by_condition', 'Group By Condition'), ('by_ages', 'Group By Ages')], max_length=50, unique=True),
        ),
    ]
