# Generated by Django 4.2.2 on 2025-02-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sqlquery_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='query_type',
            field=models.CharField(choices=[('employee_experience', 'Employee experience'), ('by_gender', 'Group By Gender'), ('by_condition', 'Group By Condition'), ('by_ages', 'Group By Ages'), ('by_rank', 'Group By Rank'), ('by_position_rank', 'Group By Position Rank')], max_length=50, unique=True),
        ),
    ]
