# Generated by Django 4.2.2 on 2025-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sqlquery_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='query_type',
            field=models.CharField(choices=[('employee_experience', 'Employee experience'), ('by_gender', 'Group By Gender'), ('by_condition', 'Group By Condition'), ('by_ages', 'Group By Ages'), ('by_rank', 'Group By Rank'), ('by_position_rank', 'Group By Position Rank'), ('count_staff', 'Group By Count Staff'), ('count_emps', 'Group By Count Emps'), ('count_stavka', 'Group By Count Stavka'), ('count_vacant', 'Group By Count Vacant')], max_length=50, unique=True),
        ),
    ]
