# Generated by Django 4.2.2 on 2025-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sqlquery_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='query_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
