# Generated by Django 4.2.2 on 2025-10-28 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_department_hik_org_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_sqlquery_query_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_links', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager_links', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_links', to='company.department')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_manager_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['department', 'is_active'], name='core_depart_departm_e3e9ca_idx'), models.Index(fields=['user'], name='core_depart_user_id_76c361_idx'), models.Index(fields=['valid_from'], name='core_depart_valid_f_51a655_idx'), models.Index(fields=['valid_until'], name='core_depart_valid_u_32ba24_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentmanager',
            constraint=models.UniqueConstraint(fields=('department', 'user'), name='uniq_department_user'),
        ),
        migrations.AddIndex(
            model_name='branchmanager',
            index=models.Index(fields=['branch', 'is_active'], name='core_branch_branch__b480c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchmanager',
            constraint=models.UniqueConstraint(fields=('branch', 'user'), name='uniq_branch_user'),
        ),
        migrations.AddConstraint(
            model_name='branchmanager',
            constraint=models.UniqueConstraint(fields=('branch', 'sort_order'), name='uniq_branch_sort_order'),
        ),
    ]
