# Generated by Django 4.2.2 on 2025-10-28 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_branchmanager_departmentmanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmanager',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
