# Generated by Django 4.2.2 on 2025-10-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_branchmanager_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branchmanager',
            name='uniq_branch_sort_order',
        ),
    ]
