# Generated by Django 4.2.2 on 2025-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_branchmanager_uniq_branch_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='face_id', max_length=50, unique=True)),
                ('last_success_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='OK', max_length=16)),
                ('outage_started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
