# Generated by Django 4.2.2 on 2025-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ingeststate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeststate',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
