# Generated by Django 4.2.2 on 2023-12-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sub_department_count',
            field=models.IntegerField(default=0),
        ),
    ]
