# Generated by Django 4.2.2 on 2023-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_department_sub_department_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='condition',
            field=models.CharField(blank=True, default='A', max_length=10, null=True),
        ),
    ]
