# Generated by Django 4.2.2 on 2024-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_is_active_department_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='local_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
