# Generated by Django 4.2.2 on 2024-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_local_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
