# Generated by Django 4.2.2 on 2024-07-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_department_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='condition',
            field=models.CharField(blank=True, default='A', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='iabs_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
