# Generated by Django 4.2.2 on 2024-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_position_condition_position_iabs_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='iabs_level_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
