# Generated by Django 4.2.2 on 2024-11-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_env_id_envmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='envmodel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
