# Generated by Django 4.2.2 on 2024-11-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_envmodel_name_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envmodel',
            old_name='name',
            new_name='name_uz',
        ),
    ]
