# Generated by Django 4.2.2 on 2024-11-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_name_envmodel_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='envmodel',
            name='logo_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
