# Generated by Django 4.2.2 on 2024-11-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_envmodel_logo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='iabs_dept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
