# Generated by Django 4.2.2 on 2024-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_department_iabs_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
