# Generated by Django 4.2.2 on 2025-04-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0053_region_lat_region_lng'),
        ('company', '0016_company_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.region'),
        ),
    ]
