# Generated by Django 4.2.2 on 2025-09-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hik_org_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
