# Generated by Django 4.2.2 on 2025-09-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_department_hik_org_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hik_org_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
