# Generated by Django 5.2.8 on 2025-11-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_department_hik_org_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_index',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
