"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import datetime
import os
from pathlib import Path

import requests
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cxsz6ne2ns6zhshw7dbn+_ry&&hq)p)t5moaynfcy-g48*lp%1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == '1'

ALLOWED_HOSTS = ['*']

# Application definition

THIRD_PARTY_APPS = [
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'rest_framework_simplejwt',
    'django_filters',
    'graphene_django',
    'channels',
    'storages',
    'django_celery_beat',
    'django_celery_results',
    # 'elasticapm.contrib.django',
]

LOCAL_APPS = [
    'apps.docflow',
    'apps.document',
    'apps.user',
    'apps.reference',
    'apps.company',
    'apps.compose',
    'apps.core',
    'apps.wcalendar',
    'apps.wchat',
    'apps.news',
    'apps.hr',
    'apps.policy',
    'apps.notification',
]

INSTALLED_APPS = [
                     'daphne',
                     'modeltranslation',
                     'django.contrib.admin',
                     'django.contrib.auth',
                     'django.contrib.contenttypes',
                     'django.contrib.sessions',
                     'django.contrib.messages',
                     'django.contrib.staticfiles',
                     'django_telegram_logging',
                     'django_extensions',
                 ] + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    # 'elasticapm.contrib.django.middleware.TracingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # corsheaders
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middlewares.request_with_token.JWTAuthenticationMiddleware',
    'config.middlewares.current_user.GlobalUserMiddleware',
    'config.middlewares.language_middleware.ActivateLanguageMiddleware',
    # 'config.middlewares.idempotency.IdempotencyMiddleware', TODO: Uncomment when front end is ready
]

CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['apps/pdf_kit/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = "user.User"

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
            'capacity': 1500,
            'expiry': 10,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'PORT': os.getenv('POSTGRES_PORT'),
        # 'ATOMIC_REQUESTS': True
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',  # Replace with your Redis configuration
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'birthday_users'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Swagger settings
SWAGGER_SETTINGS = {
    "exclude_namespaces": [],  # List URL namespaces to ignore
    "api_version": '0.1',  # Specify your API's version
    "api_path": "/",  # Specify the path to your API not a root level
    "enabled_methods": [  # Specify which methods to enable in Swagger UI
        'get',
        'post',
        'put',
        'patch',
        'delete'
    ],
    "api_key": 'Authorization ',  # An API key
    "is_authenticated": False,  # Set to True to enforce user authentication,
    "is_superuser": False,  # Set to True to enforce admin only access
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        }
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True
gettext = lambda s: s
LANGUAGES = (
    ('uz', gettext('Uzbek')),
    ('ru', gettext('Russian')),
    ('en', gettext('English')),
)

USE_TZ = True
TIME_ZONE = 'Asia/Tashkent'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# SFTP Settings
DEFAULT_FILE_STORAGE = 'config.storage.CustomSFTPStorage'
sftp_params = {
    "password": os.getenv('SFTP_PASSWORD'),
    "username": os.getenv('SFTP_USER')
}

SFTP_STORAGE_HOST = os.getenv('STORAGE_HOST')
SFTP_STORAGE_ROOT = os.getenv('STORAGE_PATH')
SFTP_STORAGE_PARAMS = sftp_params
SFTP_STORAGE_INTERACTIVE = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_IMPORTS = (
    'apps.compose.tasks',
    'apps.news.tasks',
    'apps.wchat.tasks',
    'apps.hr.tasks',
)
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TASK_SEND_SENT_EVENT = True  # Tracks task arguments
CELERY_RESULT_EXTENDED = True  # Stores args & kwargs in result backend
CELERY_APP_NAME = "config"
BROKER_URL = 'redis://localhost:6379/0'
CELERY_TIMEZONE = 'Asia/Tashkent'

# CELERY BEAT
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Rest Framework Configurations
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),

    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # # 'DATE_FORMATS': [('%d.%m.%Y')],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%f%z',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'COERCE_DECIMAL_TO_STRING': False,
    # "EXCEPTION_HANDLER": "utils.base_exception.base_exception_handler",
}

# JWT Configurations
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=1),
}

# Logging Configurations
if not DEBUG:
    TELEGRAM_LOGGING_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
    TELEGRAM_LOGGING_CHAT = -1001652185350
    TELEGRAM_LOGGING_EMIT_ON_DEBUG = False

    LOGGING = {
        'version': 1,
        'handlers': {
            'telegram': {
                'level': 'ERROR',
                'class': 'django_telegram_logging.handler.TelegramHandler',
            }
        },
        'loggers': {
            'django': {
                'level': 'ERROR',
                'handlers': ['telegram'],
            }
        }
    }

# def is_apm_server_reachable(server_url):
#     try:
#         resp = requests.get(f"{server_url}/", timeout=2)
#         return resp.status_code < 500
#     except Exception:
#         return False
#
#
# # Set your APM server
# APM_SERVER_URL = os.getenv('http://139.59.127.161:8200', 'http://localhost:8200')
#
# if is_apm_server_reachable(APM_SERVER_URL):
#     # Elastic APM Configurations
#     if not DEBUG:
#         ELASTIC_APM = {
#             "SERVICE_NAME": "Digital Workspace",
#             "SECRET_TOKEN": "",
#             "SERVER_URL": "http://139.59.127.161:8200",
#             "ENVIRONMENT": "production",
#             "CAPTURE_BODY": "all",
#         }
#     else:
#         ELASTIC_APM = {
#             "SERVICE_NAME": "my-django-app",
#             "SECRET_TOKEN": "",  # Keep empty if security is disabled
#             "SERVER_URL": "http://localhost:8200",
#             # "API_KEY": "aTF6Q0tKWUIyWmZ4UjdENVpUVTc6STRSRGg4MWpTWUdLZFNXMU9qaDhEdw==",
#             "ENVIRONMENT": "development",
#             "CAPTURE_BODY": "all",
#             "DEBUG": False,
#             "ENABLED": False,
#         }


# Idempotency key expiry (seconds)
IDEMPOTENCY_KEY_EXPIRY = 60 * 60 * 24  # 24 hours
