# Generated by Django 4.2.2 on 2023-11-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_department'),
        ('document', '0002_file_created_by_file_created_date_file_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
    ]
