# Generated by Django 4.2.2 on 2023-12-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_file_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
