# Generated by Django 4.2.2 on 2023-12-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_file_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
