# Generated by Django 4.2.2 on 2024-01-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_file_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
