# Generated by Django 4.2.2 on 2024-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_file_extension_file_file_size'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['key', 'name', 'extension'], name='document_fi_key_38da3b_idx'),
        ),
    ]
