# Generated by Django 4.2.2 on 2024-08-24 06:11

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_file_document_fi_key_38da3b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to=''),
        ),
    ]
