# Generated by Django 4.2.2 on 2024-08-24 07:41

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=config.storage.CustomSFTPStorage(), upload_to=''),
        ),
    ]
