# Generated by Django 4.2.2 on 2025-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
