# Generated by Django 4.2.2 on 2025-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_file_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
