# Generated by Django 4.2.2 on 2025-02-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_file_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
