# Generated by Django 4.2.2 on 2025-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_mobileapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapplication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='apps/'),
        ),
    ]
