# Generated by Django 4.2.2 on 2025-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_alter_mobileapplication_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileapplication',
            name='type',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'IOS'), ('desktop', 'Desktop'), ('chat_android', 'Chat Android'), ('chat_ios', 'Chat IOS')], max_length=50, unique=True),
        ),
    ]
