# Generated by Django 4.2.2 on 2025-08-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_alter_mobileapplication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='bucket',
            field=models.CharField(db_index=True, default='app-prod-docs', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='etag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='state',
            field=models.CharField(db_index=True, default='uploaded', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='version_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
