# Generated by Django 4.2.2 on 2025-09-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_file_bucket_file_etag_file_sha256_file_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
