# Generated by Django 4.2.2 on 2025-10-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_alter_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
