# Generated by Django 4.2.2 on 2025-10-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
    ]
