# Generated by Django 4.2.2 on 2025-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds. If file is audio or video or voice.', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='peaks',
            field=models.JSONField(blank=True, help_text='Audio peaks data. If file is audio or voice.', null=True),
        ),
    ]
