# Generated by Django 4.2.2 on 2025-10-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_file_duration_file_peaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='peaks',
            field=models.JSONField(blank=True, default=list, help_text='Audio peaks data. If file is audio or voice.', null=True),
        ),
    ]
