# Generated by Django 4.2.2 on 2025-04-19 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0017_company_region'),
        ('hr', '0002_payrollcategory_payrollsubcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollcategory',
            options={'verbose_name': 'Payroll Category', 'verbose_name_plural': 'Payroll Categories'},
        ),
        migrations.AlterModelOptions(
            name='payrollsubcategory',
            options={'verbose_name': 'Payroll SubCategory', 'verbose_name_plural': 'Payroll SubCategories'},
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('period', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pay_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='hr.payrollsubcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
