# Generated by Django 4.2.2 on 2025-04-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_payrollcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='pay_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='hr.payrollsubcategory'),
        ),
    ]
