# Generated by Django 4.2.2 on 2025-05-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_region'),
        ('hr', '0004_alter_payroll_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division', to='company.department'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_department', to='company.department'),
        ),
    ]
