# Generated by Django 4.2.2 on 2025-09-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_yearmodel_iabscalendar_dailysummary_attendanceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabscalendar',
            name='holiday_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
