# Generated by Django 4.2.2 on 2025-09-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_iabscalendar_holiday_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearmodel',
            name='year',
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
    ]
