# Generated by Django 4.2.2 on 2025-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_yearmodel_year'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iabscalendar',
            index=models.Index(fields=['year', 'date'], name='hr_iabscale_year_id_a11606_idx'),
        ),
        migrations.AddIndex(
            model_name='iabscalendar',
            index=models.Index(fields=['date'], name='hr_iabscale_date_9e3d59_idx'),
        ),
        migrations.AddConstraint(
            model_name='iabscalendar',
            constraint=models.UniqueConstraint(fields=('year', 'date'), name='uniq_iabscalendar_year_date'),
        ),
    ]
