# Generated by Django 4.2.2 on 2025-09-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_iabscalendar_hr_iabscale_year_id_a11606_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='week_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
