# Generated by Django 4.2.2 on 2025-09-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_dailysummary_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='person_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='person_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='plan_begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='plan_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
