# Generated by Django 4.2.2 on 2025-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_dailysummary_person_code_dailysummary_person_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='check_in_status',
            field=models.CharField(choices=[('Vaqtida keldi', 'Vaqtida keldi'), ('Sababli', 'Sababli'), ('Qayd etilmagan', 'Kechikdi'), ('Kechikdi', 'Kechikdi'), ('Kelmadi', 'Kechikdi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='check_out_status',
            field=models.CharField(choices=[('Erta ketdi', 'Erta ketdi'), ('Sababli', 'Sababli'), ('Vaqtida ketdi', 'Vaqtida ketdi'), ('Qayd etilmagan', 'Qayd etilmagan'), ('Kelmadi', 'Kelmadi')], max_length=50, null=True),
        ),
    ]
