# Generated by Django 4.2.2 on 2025-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_dailysummary_check_in_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='has_reason',
            field=models.BooleanField(default=False),
        ),
    ]
