# Generated by Django 4.2.2 on 2025-10-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_alter_user_hik_person_code'),
        ('hr', '0013_dailysummary_has_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='user_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userstatus'),
        ),
    ]
