# Generated by Django 4.2.2 on 2025-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_dailysummary_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='check_in_status',
            field=models.CharField(choices=[('Vaqtida keldi', 'Vaqtida keldi'), ('Sababli', 'Sababli'), ('Qayd etilmagan', 'Kechikdi'), ('Kechikdi', 'Kechikdi'), ('Kelmadi', 'Kelmadi')], max_length=50, null=True),
        ),
    ]
