# Generated by Django 4.2.2 on 2025-10-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_alter_dailysummary_check_in_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='check_in_status',
            field=models.CharField(choices=[('came-on-time', 'Vaqtida keldi'), ('excused', 'Sababli'), ('no-entry-marked', 'Kechikdi'), ('late-arrival', 'Kechikdi'), ('not-came', 'Kelmadi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='check_out_status',
            field=models.CharField(choices=[('early-departure', 'Erta ketdi'), ('excused', 'Sababli'), ('normal-exit', 'Vaqtida ketdi'), ('no-exit-marked', 'Qayd etilmagan'), ('not-came', 'Kelmadi')], max_length=50, null=True),
        ),
    ]
