# Generated by Django 4.2.2 on 2025-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
