# Generated by Django 4.2.2 on 2025-10-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_workschedule_name_en_workschedule_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'ordering': ('-created_date', '-id')},
        ),
    ]
