# Generated by Django 4.2.2 on 2025-10-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_employeeschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='work_schedule',
            new_name='schedule',
        ),
    ]
