# Generated by Django 4.2.2 on 2025-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_employeeschedule_is_default_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['employee'], name='hr_employee_employe_7339ae_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['schedule'], name='hr_employee_schedul_6075c2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedule',
            index=models.Index(fields=['employee', 'is_default'], name='hr_employee_employe_cfcceb_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeschedule',
            constraint=models.UniqueConstraint(fields=('employee', 'schedule'), name='uniq_employee_schedule_pair'),
        ),
    ]
