# Generated by Django 4.2.2 on 2025-10-22 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0019_alter_department_hik_org_code'),
        ('hr', '0023_employeeschedule_hr_employee_employe_7339ae_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDepartmentScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_approve', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_scopes', to='company.department')),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_scopes', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Department Scope',
                'verbose_name_plural': 'HR Department Scopes',
                'indexes': [models.Index(fields=['hr_user', 'department'], name='hr_hrdepart_hr_user_84e104_idx'), models.Index(fields=['department'], name='hr_hrdepart_departm_3342d1_idx'), models.Index(fields=['hr_user'], name='hr_hrdepart_hr_user_d72528_idx')],
                'unique_together': {('hr_user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='HRBranchScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_approve', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_scopes', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_scopes', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Branch Scope',
                'verbose_name_plural': 'HR Branch Scopes',
                'indexes': [models.Index(fields=['hr_user', 'branch'], name='hr_hrbranch_hr_user_930769_idx'), models.Index(fields=['branch'], name='hr_hrbranch_branch__315a62_idx'), models.Index(fields=['hr_user'], name='hr_hrbranch_hr_user_922f97_idx')],
                'unique_together': {('hr_user', 'branch')},
            },
        ),
    ]
