# Generated by Django 4.2.2 on 2025-10-24 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_alter_file_peaks'),
        ('reference', '0061_attendancereason_delete_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0024_hrdepartmentscope_hrbranchscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('late', 'Late'), ('absent', 'Absent'), ('early_leave', 'Early leave'), ('missed_checkin', 'Missed check-in'), ('missed_checkout', 'Missed check-out')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('worked_time', models.IntegerField(blank=True, help_text='Corrected worked time in seconds, set by HR user when handling the exception', null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='document.file')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='hr.dailysummary')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_exceptions', to=settings.AUTH_USER_MODEL)),
                ('hr_user', models.ForeignKey(blank=True, help_text='HR user who may correct worked time, they can add or subtract time based on the exception', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_attendance_exceptions', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='reference.attendancereason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
