# Generated by Django 4.2.2 on 2025-10-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_attendanceexception'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceexception',
            old_name='user',
            new_name='employee',
        ),
    ]
