# Generated by Django 4.2.2 on 2025-10-27 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0026_rename_user_attendanceexception_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceexception',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_exceptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
