# Generated by Django 4.2.2 on 2025-10-28 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0027_alter_attendanceexception_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceexception',
            name='decided_at',
        ),
        migrations.RemoveField(
            model_name='attendanceexception',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='attendanceexception',
            name='decision_note',
        ),
        migrations.RemoveField(
            model_name='attendanceexception',
            name='hr_user',
        ),
        migrations.CreateModel(
            name='AttendanceExceptionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('director', 'Director'), ('hr', 'HR')], max_length=30)),
                ('is_approved', models.BooleanField(null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('action_time', models.DateTimeField(blank=True, null=True)),
                ('exception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hr.attendanceexception')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
