# Generated by Django 4.2.2 on 2025-10-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0028_remove_attendanceexception_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceexception',
            name='hr_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceexception',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceexceptionapproval',
            name='type',
            field=models.CharField(choices=[('manager', 'Manager'), ('hr', 'HR')], max_length=30),
        ),
    ]
