# Generated by Django 4.2.2 on 2025-11-04 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0019_alter_department_hik_org_code'),
        ('hr', '0029_attendanceexception_hr_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('mid_pay_date', models.DateField(blank=True, help_text='Avans pay date', null=True)),
                ('final_pay_date', models.DateField(blank=True, help_text='Final pay date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('frozen', 'Frozen (locked)')], default='draft', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_vacation', models.PositiveSmallIntegerField(default=0)),
                ('total_sick', models.PositiveSmallIntegerField(default=0)),
                ('total_trip', models.PositiveSmallIntegerField(default=0)),
                ('total_absent', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='hr.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=8)),
                ('kind', models.CharField(choices=[('work', 'Worked'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('trip', 'Business Trip'), ('absent', 'Absent'), ('off', 'Weekend/Holiday')], max_length=16)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='hr.payrollrow')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided', models.BooleanField(default=False)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hr.payrollperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='payrollrow',
            index=models.Index(fields=['period', 'employee'], name='hr_payrollr_period__a18f9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrow',
            unique_together={('period', 'employee')},
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['company', 'year', 'month'], name='hr_payrollp_company_0a33e7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status'], name='hr_payrollp_status_55dda7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('company', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='payrollcell',
            index=models.Index(fields=['row'], name='hr_payrollc_row_id_012e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcell',
            index=models.Index(fields=['date'], name='hr_payrollc_date_c3ed08_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcell',
            index=models.Index(fields=['kind'], name='hr_payrollc_kind_00db90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcell',
            unique_together={('row', 'date')},
        ),
        migrations.AddIndex(
            model_name='payrollapproval',
            index=models.Index(fields=['period', 'decided'], name='hr_payrolla_period__f23073_idx'),
        ),
    ]
