# Generated by Django 4.2.2 on 2025-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_attendanceexception_hr_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='lunch_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='lunch_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
