# Generated by Django 4.2.2 on 2025-11-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_department_hik_org_code'),
        ('hr', '0030_payrollperiod_payrollrow_payrollcell_payrollapproval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
        migrations.AlterField(
            model_name='payrollrow',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
    ]
