# Generated by Django 4.2.2 on 2025-11-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_department_hik_org_code'),
        ('hr', '0031_alter_payrollperiod_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollperiod',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
    ]
