# Generated by Django 4.2.2 on 2025-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_workschedule_lunch_end_time_and_more'),
        ('hr', '0032_alter_payrollperiod_company'),
    ]

    operations = [
    ]
