# Generated by Django 4.2.2 on 2025-11-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0101_compose_additional_data'),
        ('hr', '0033_merge_20251104_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceexception',
            name='explanation_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explanation_letter', to='compose.compose'),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='check_in_status',
            field=models.CharField(choices=[('came-on-time', 'Vaqtida keldi'), ('excused', 'Sababli'), ('no-entry-marked', 'Kirish qayd etilmagan'), ('late-arrival', 'Kechikdi'), ('not-came', 'Kelmadi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='check_out_status',
            field=models.CharField(choices=[('early-departure', 'Erta ketdi'), ('excused', 'Sababli'), ('normal-exit', 'Vaqtida ketdi'), ('no-exit-marked', 'Chiqish qayd etilmagan'), ('not-came', 'Kelmadi')], max_length=50, null=True),
        ),
    ]
