# Generated by Django 4.2.2 on 2025-11-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_attendanceexception_explanation_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcell',
            name='kind',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
