# Generated by Django 4.2.2 on 2025-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_alter_payrollcell_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcell',
            name='kind',
            field=models.CharField(choices=[('work', 'Worked'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('trip', 'Business Trip'), ('absent', 'Absent'), ('off', 'Weekend/Holiday')], max_length=50, null=True),
        ),
    ]
