# Generated by Django 4.2.2 on 2025-11-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0036_alter_payrollcell_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='department',
        ),
    ]
