# Generated by Django 4.2.2 on 2025-11-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_remove_payrollperiod_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrbranchscope',
            old_name='valid_to',
            new_name='valid_until',
        ),
        migrations.RenameField(
            model_name='hrdepartmentscope',
            old_name='valid_to',
            new_name='valid_until',
        ),
    ]
