# Generated by Django 4.2.2 on 2025-11-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_department_hik_org_code'),
        ('hr', '0038_rename_valid_to_hrbranchscope_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='type',
            field=models.CharField(choices=[('department', 'Department'), ('branch', 'Branch')], default='department', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('company', 'department', 'year', 'month')},
        ),
    ]
