# Generated by Django 4.2.2 on 2025-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0039_alter_payrollperiod_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='final_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='mid_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='mid_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
