# Generated by Django 4.2.2 on 2025-10-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_telegrampairrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrampairrequest',
            name='request_token',
            field=models.TextField(unique=True),
        ),
    ]
