# Generated by Django 4.2.2 on 2025-10-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_telegrampairrequest_request_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampairrequest',
            name='telegram_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
