# Generated by Django 4.2.2 on 2023-07-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
