# Generated by Django 4.2.2 on 2023-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_statusmodel_name_en_statusmodel_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
