# Generated by Django 4.2.2 on 2023-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_statusmodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='name_uz',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
