# Generated by Django 4.2.2 on 2023-07-08 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0007_statusmodel_description_uz_statusmodel_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('message_uz', models.CharField(max_length=255, null=True)),
                ('message_en', models.CharField(max_length=255, null=True)),
                ('message_ru', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=20)),
                ('status_code', models.CharField(max_length=10)),
                ('code', models.IntegerField(db_index=True, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
