# Generated by Django 4.2.2 on 2023-07-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_errormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errormessage',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='name_en',
        ),
    ]
