# Generated by Django 4.2.2 on 2023-07-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_remove_errormessage_message_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errormessage',
            name='message_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
