# Generated by Django 4.2.2 on 2023-07-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_errormessage_message_en_statusmodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdescription',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shortdescription',
            name='description_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shortdescription',
            name='description_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
