# Generated by Django 4.2.2 on 2023-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0012_actionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondent',
            name='tin',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
