# Generated by Django 4.2.2 on 2023-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0018_actiondescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondescription',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
