# Generated by Django 4.2.2 on 2023-08-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0019_actiondescription_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondescription',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
