# Generated by Django 4.2.2 on 2023-08-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0020_alter_actiondescription_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actiondescription',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actiondescription',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actiondescription',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
