# Generated by Django 4.2.2 on 2023-08-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0021_alter_actiondescription_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionmodel',
            name='description',
        ),
    ]
