# Generated by Django 4.2.2 on 2023-08-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0022_remove_actionmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionmodel',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.actiondescription'),
        ),
    ]
