# Generated by Django 4.2.2 on 2023-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0025_alter_district_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_for_compose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_for_compose',
            field=models.BooleanField(default=False),
        ),
    ]
