# Generated by Django 4.2.2 on 2024-01-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0031_actiondescription_is_active_actionmodel_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondent',
            old_name='tin',
            new_name='pinfl',
        ),
    ]
