# Generated by Django 4.2.2 on 2024-01-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0032_rename_tin_correspondent_pinfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='tin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
