# Generated by Django 4.2.2 on 2024-01-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0033_correspondent_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondent',
            name='type',
            field=models.CharField(choices=[('physical', 'PHYSICAL'), ('legal', 'LEGAL'), ('entrepreneur', 'ENTREPRENEUR')], max_length=15),
        ),
    ]
