# Generated by Django 4.2.2 on 2024-01-11 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0034_alter_correspondent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSignInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_id', models.CharField(max_length=100, null=True)),
                ('pkcs7', models.TextField(null=True)),
                ('pkcs7_info', models.JSONField(null=True)),
                ('signed', models.BooleanField(default=False)),
                ('ip_addr', models.CharField(max_length=255, null=True)),
                ('signed_on', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
