# Generated by Django 4.2.2 on 2024-01-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_file_extension_file_file_size'),
        ('reference', '0035_digitalsigninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.file'),
        ),
    ]
