# Generated by Django 4.2.2 on 2024-01-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0036_journal_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
