# Generated by Django 4.2.2 on 2024-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0037_journal_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondescription',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actiondescription',
            name='icon_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
