# Generated by Django 4.2.2 on 2024-01-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0038_actiondescription_color_actiondescription_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
