# Generated by Django 4.2.2 on 2024-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0040_documenttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
