# Generated by Django 4.2.2 on 2024-02-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0041_district_code_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
