# Generated by Django 4.2.2 on 2024-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0042_journal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
