# Generated by Django 4.2.2 on 2024-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0043_statusmodel_is_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentsubtype',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentsubtype',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
