# Generated by Django 4.2.2 on 2024-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0044_documentsubtype_name_en_documentsubtype_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
