# Generated by Django 4.2.2 on 2024-10-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0046_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsigninfo',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
