# Generated by Django 4.2.2 on 2024-12-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0048_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
