# Generated by Django 4.2.2 on 2024-12-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0050_country_currency_code_region_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
