# Generated by Django 4.2.2 on 2025-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0052_editablefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
