# Generated by Django 4.2.2 on 2025-04-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_mobileapplication'),
        ('reference', '0054_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.mobileapplication'),
        ),
    ]
