# Generated by Django 4.2.2 on 2025-05-12 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0055_appversion_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('distance', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='reference.region')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='reference.region')),
            ],
            options={
                'unique_together': {('from_city', 'to_city')},
            },
        ),
    ]
