# Generated by Django 4.2.2 on 2025-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0057_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdescription',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
