# Generated by Django 4.2.2 on 2025-11-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0062_exceptionemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceptionemployee',
            options={'ordering': ('-is_active', '-created_date', '-id'), 'verbose_name': 'Exception employee', 'verbose_name_plural': 'Exception employees'},
        ),
    ]
