# Generated by Django 4.2.2 on 2025-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0063_alter_exceptionemployee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionemployee',
            name='activation_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceptionemployee',
            name='deactivation_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
