# Generated by Django 4.2.2 on 2024-10-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmodel',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarmodel',
            name='notify_by',
            field=models.CharField(blank=True, choices=[('system', 'system'), ('email', 'email'), ('sms', 'sms')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calendarmodel',
            name='source',
            field=models.CharField(blank=True, choices=[('zoom', 'zoom'), ('cisco', 'cisco')], max_length=20, null=True),
        ),
    ]
