# Generated by Django 4.2.2 on 2024-10-29 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wcalendar', '0002_calendarmodel_link_calendarmodel_notify_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calendarmodel',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
