# Generated by Django 4.2.2 on 2024-02-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0003_alter_chatmessage_chat_alter_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
