# Generated by Django 4.2.2 on 2025-01-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0006_alter_chatmessagefile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatimage',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatimage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wchat.chat'),
        ),
    ]
