# Generated by Django 4.2.2 on 2025-01-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0007_chatimage_is_placed_alter_chatimage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='wchat.chatmessage'),
        ),
    ]
