# Generated by Django 4.2.2 on 2025-02-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0008_chat_last_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatimage',
            options={'ordering': ['-is_placed']},
        ),
    ]
