# Generated by Django 4.2.2 on 2025-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0009_alter_chatimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='edited_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
