# Generated by Django 4.2.2 on 2025-02-15 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wchat', '0011_chatmessagereaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmessagereaction',
            unique_together={('message', 'user')},
        ),
    ]
