# Generated by Django 4.2.2 on 2025-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0012_alter_chatmessagereaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
