# Generated by Django 4.2.2 on 2025-02-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0013_chat_deleted_chat_deleted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'Link')], default='text', max_length=30, null=True),
        ),
    ]
