# Generated by Django 4.2.2 on 2025-04-07 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0014_alter_chatmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
