# Generated by Django 4.2.2 on 2025-04-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0015_chat_uid_chatmessage_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='on_mute',
            field=models.BooleanField(default=False),
        ),
    ]
