# Generated by Django 4.2.2 on 2025-10-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0016_chatmember_on_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagefile',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds. If message is audio or video or voice.', null=True),
        ),
        migrations.AddField(
            model_name='chatmessagefile',
            name='peaks',
            field=models.JSONField(blank=True, help_text='Audio peaks data. If message is audio or voice.', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'Link'), ('voice', 'Voice')], default='text', max_length=30, null=True),
        ),
    ]
