# Generated by Django 4.2.2 on 2025-10-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0017_chatmessagefile_duration_chatmessagefile_peaks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagefile',
            name='peaks',
            field=models.JSONField(default=list, help_text='Audio peaks data. If message is audio or voice.'),
        ),
    ]
