# Generated by Django 4.2.2 on 2025-10-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wchat', '0018_alter_chatmessagefile_peaks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessagefile',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='chatmessagefile',
            name='peaks',
        ),
    ]
